case $- in
  *i*) ;;
  *) return ;;
esac

# Avoid duplicate hooks when .profile also sources .bashrc.
[[ ${dotfiles_bash_loaded-} == yes ]] && return
dotfiles_bash_loaded=yes

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# Called by the completion module.
# shellcheck disable=SC2329
dotfiles_bash_source_if_readable() {
  [[ -r $1 ]] || return 0
  source "$@"
}

source "$XDG_CONFIG_HOME/bash/conf.d/plugins.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/mise.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/env.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/options.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/history.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/keybindings.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/functions.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/completion.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/fzf.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/zoxide.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/prompt.bash"
source "$XDG_CONFIG_HOME/bash/conf.d/aliases.bash"
unset -f dotfiles_bash_source_if_readable

if [[ -n ${BLE_VERSION-} ]]; then
  ble-attach
fi

if [ -r "$XDG_CONFIG_HOME/bash/conf.d/noctalia.bash" ]; then
  . "$XDG_CONFIG_HOME/bash/conf.d/noctalia.bash"
fi
